---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Ensure GlusterFS is started and enabled at boot.
  service: "name={{ glusterfs_daemon }} state=started enabled=yes"
  when: glusterfs_server == "yes"

- name: Ensure brick directories are present.
  file: dest={{ item }} state=directory
  with_items: glusterfs_bricks
  when: glusterfs_server == "yes"

- name: Ensure GlusterFS volumes are created.
  gluster_volume:
    name={{ glusterfs_volume_name }}
    bricks={{ glusterfs_bricks | join(",") }}
    force={{ glusterfs_force | default("no") }}
    state=present
  when: glusterfs_server == "yes" and glusterfs_volume_name != "" and glusterfs_bricks != []

- name: Ensure GlusterFS volumes are started
  gluster_volume: name={{ glusterfs_volume_name }} state=started
  when: glusterfs_server == "yes" and glusterfs_volume_name != ""

- name: Ensure GlusterFS mount points exist.
  file:
    dest={{ item.name }}
    state=directory
  with_items: glusterfs_mount_points
  when: glusterfs_client == "yes"

- name: Ensure GlusterFS mount entries are present in /etc/fstab.
  mount:
    name={{ item.name }}
    src={{ item.src }}
    fstype=glusterfs
    state=present
  with_items: glusterfs_mount_points
  when: glusterfs_client == "yes"

- name: Ensure GlusterFS entries are mounted.
  mount:
    name={{ item.name }}
    src={{ item.src }}
    fstype=glusterfs
    opts=rw,acl
    state=mounted
  with_items: glusterfs_mount_points
  when: glusterfs_client == "yes"

- name: Ensure GlusterFS ACLs are set.
  acl:
    name={{ item.name }}
    etype=user
    entity={{ glusterfs_mount_owner }}
    permissions=rwx
    state=present
  with_items: glusterfs_mount_points
  when: glusterfs_client == "yes"

- name: Ensure GlusterFS default ACLs are set.
  acl:
    name={{ item.name }}
    etype=user
    entity={{ glusterfs_mount_owner }}
    permissions=rwx
    default=yes
    state=present
  with_items: glusterfs_mount_points
  when: glusterfs_client == "yes"
